In [ ]:
1. Write a Python Program to Add Two Matrices?

In [4]:
import numpy as np
m1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

m2 = np.array([[10, 11, 12],
                [13, 14, 15],
                16, 17, 18]])

result = m1+m2

print(result)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [5]:
matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[10, 11, 12],
           [13, 14, 15],
           [16, 17, 18]]

# Define a matrix to store the result
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

# Iterate through each element of the matrices and add them
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]

# Print the result
for row in result:
    print(row)

[11, 13, 15]
[17, 19, 21]
[23, 25, 27]


In [ ]:
***************************************************************************************************************************

In [ ]:
2. Write a Python Program to Multiply Two Matrices?

In [7]:
import numpy as np
m1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

m2 = np.array([[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])

mul = m1*m2

print(mul)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [ ]:
***************************************************************************************************************************

In [ ]:
3. Write a Python Program to Transpose a Matrix?

In [6]:
matrix = [[1,2],
          [4,5],
          [7,8]]

print("Befor Transpose matrix")
for i in matrix :
    print(i)
    
# create an empty matrix with swapped dimensions

transpose_matrix = [[0, 0, 0],
                    [0, 0, 0]]

for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        transpose_matrix[j][i] = matrix[i][j]
        
print("After Transpose:")
for row in transpose_matrix:
    print(row)

Befor Transpose matrix
[1, 2]
[4, 5]
[7, 8]
After Transpose:
[1, 4, 7]
[2, 5, 8]


In [ ]:
***************************************************************************************************************************

In [ ]:
4. Write a Python Program to Sort Words in Alphabetic Order?

In [13]:
# take user input string
input_str = input("Enter a string: ")

# split the string into words
words = input_str.split()
print(words)

# sort the words
words.sort()

# display the sorted words
print("Sorted words:")
for word in words:
    print(word)

Enter a string: Write a Python Program to Sort Words in Alphabetic Order
['Write', 'a', 'Python', 'Program', 'to', 'Sort', 'Words', 'in', 'Alphabetic', 'Order']
Sorted words:
Alphabetic
Order
Program
Python
Sort
Words
Write
a
in
to


In [ ]:
***************************************************************************************************************************

In [ ]:
5. Write a Python Program to Remove Punctuation From a String

In [24]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

input_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in input_str:
    if char not in punctuations:
        no_punct += char

# display the string without punctuation
print("String without punctuation :", no_punct)



Enter a string: This is Assignment_No.7_FSDS2.0
String without punctuation : This is AssignmentNo7FSDS20


In [ ]:
***************************************************************************************************************************